# Generated by Django 3.0.2 on 2020-01-26 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=20)),
                ('location', models.TextField(max_length=200)),
                ('mobile', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_amount', models.DecimalField(decimal_places=2, max_digits=200)),
                ('d_status', models.TextField(max_length=30)),
                ('d_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=20)),
                ('p_type', models.CharField(max_length=30)),
                ('p_cost', models.DecimalField(decimal_places=2, max_digits=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_name', models.CharField(max_length=20)),
                ('v_location', models.TextField(max_length=100)),
                ('v_mobile', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('c_quantity', models.IntegerField(blank=True, null=True)),
                ('c_total', models.DecimalField(blank=True, decimal_places=2, max_digits=200, null=True)),
                ('c_customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='product.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='VendorCostSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Changed_amount', models.DecimalField(decimal_places=2, max_digits=200)),
                ('product_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Products')),
                ('vendor_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Vender')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='vender',
            field=models.ManyToManyField(to='product.Vender'),
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Products')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_status', models.TextField()),
                ('o_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Customer')),
                ('c_cart', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Cart')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_quantity', models.IntegerField()),
                ('b_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('order', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='product.Order')),
                ('product', models.ManyToManyField(to='product.Products')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='c_product',
            field=models.ManyToManyField(blank=True, to='product.Products'),
        ),
    ]
