# Generated by Django 3.0.2 on 2020-01-06 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_quantity', models.IntegerField()),
                ('b_amount', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=20)),
                ('location', models.TextField(max_length=200)),
                ('mobile', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_amount', models.DecimalField(decimal_places=2, max_digits=200)),
                ('d_status', models.TextField(max_length=30)),
                ('d_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_status', models.TextField()),
                ('o_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Bill')),
                ('o_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=20)),
                ('p_type', models.CharField(max_length=30)),
                ('p_cost', models.DecimalField(decimal_places=2, max_digits=200)),
                ('p_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_name', models.CharField(max_length=20)),
                ('v_location', models.TextField(max_length=100)),
                ('v_mobile', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='products',
            name='vender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Vender'),
        ),
        migrations.AddField(
            model_name='order',
            name='o_vender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Vender'),
        ),
        migrations.AddField(
            model_name='bill',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Products'),
        ),
    ]
