# Generated by Django 3.0.2 on 2020-01-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20200106_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='customer',
            field=models.ManyToManyField(blank=True, to='product.Customer'),
        ),
    ]
