# Generated by Django 3.0.2 on 2020-01-08 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20200108_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='o_bill',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.Bill'),
        ),
    ]
