# Generated by Django 3.0.2 on 2020-01-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20200108_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField()),
                ('sessions_id', models.TextField()),
                ('b_quantity', models.IntegerField()),
                ('c_product', models.ManyToManyField(blank=True, to='product.Products')),
            ],
        ),
    ]
