# Generated by Django 3.0.2 on 2020-01-08 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='b_quantity',
            new_name='c_quantity',
        ),
        migrations.AddField(
            model_name='cart',
            name='c_order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Order'),
        ),
    ]
