# Generated by Django 3.0.2 on 2020-01-09 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20200108_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='o_user',
            field=models.ManyToManyField(blank=True, to='product.Customer'),
        ),
    ]
