# Generated by Django 3.0.2 on 2020-01-09 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20200109_0422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='o_bill',
        ),
        migrations.RemoveField(
            model_name='order',
            name='o_user',
        ),
        migrations.AddField(
            model_name='bill',
            name='o_order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Order'),
        ),
        migrations.AddField(
            model_name='customer',
            name='o_user',
            field=models.ManyToManyField(blank=True, to='product.Order'),
        ),
    ]
