# Generated by Django 3.0.2 on 2020-01-09 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20200109_0425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='o_user',
            new_name='order',
        ),
    ]
