# Generated by Django 3.0.2 on 2020-01-09 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20200109_0426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='o_order',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='o_bill',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='product.Bill'),
        ),
        migrations.AddField(
            model_name='order',
            name='o_user',
            field=models.ManyToManyField(to='product.Customer'),
        ),
    ]
