# Generated by Django 3.0.2 on 2020-01-09 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20200109_0432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='o_bill',
        ),
        migrations.AddField(
            model_name='bill',
            name='order',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='product.Order'),
        ),
    ]
